# [Settings]

[build]
  base = "/"
  publish = "public/"
  command = "gatsby build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  # package = "@netlify/plugin-gatsby"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  directory = "netlify/functions/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    # Cache Control
    cache-control = '''
      public
      max-age=0,
      no-cache,
      no-store,
      must-revalidate
    '''
