# [Settings]

[build]
  base = "/"
  publish = "public/"
  command = "gatsby build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  # package = "@netlify/plugin-gatsby"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  directory = "netlify/functions/"
